export const expenseFromRow = (r) => ({
  id: r.id,
  date: r.date,
  propertyId: r.property_id || '',
  roomId: r.room_id || '',
  category: r.category || '',
  content: r.content || '',
  payee: r.payee || '',
  amount: r.amount ?? 0,
  payeeId: r.payee_id || '',
  payeeType: r.payee_type || '',
  paymentMethod: r.payment_method || '',
  hasReceipt: !!r.has_receipt,
  paidDate: r.paid_date || '',
  taxType: r.tax_type || '',
  isCapitalExpenditure: !!r.is_capital_expenditure,
  source: r.source || 'manual',
  sourceRef: r.source_ref || '',
  invoiceNumber: r.invoice_number || '',
  contractId: r.contract_id || '',
  counterparty: r.counterparty || '',
  counterpartyId: r.counterparty_id || '',
  counterpartyType: r.counterparty_type || '',
  payerName: r.payer_name || '',
  depositAccount: r.deposit_account || '',
  depositDate: r.deposit_date || '',
  trustAmount: r.trust_amount ?? '',
  trustRemitAmount: r.trust_remit_amount ?? '',
  note: r.note || '',
})

export const expenseToRow = (e) => ({
  date: e.date,
  property_id: e.propertyId || null,
  room_id: e.roomId || null,
  category: e.category || null,
  content: e.content || null,
  payee: e.payee || null,
  amount: e.amount || 0,
  payee_id: e.payeeId || null,
  payee_type: e.payeeType || null,
  payment_method: e.paymentMethod || null,
  has_receipt: !!e.hasReceipt,
  paid_date: e.paidDate || null,
  tax_type: e.taxType || null,
  is_capital_expenditure: !!e.isCapitalExpenditure,
  source: e.source || 'manual',
  source_ref: e.sourceRef || null,
  invoice_number: e.invoiceNumber || null,
  contract_id: e.contractId || null,
  counterparty: e.counterparty || null,
  counterparty_id: e.counterpartyId || null,
  counterparty_type: e.counterpartyType || null,
  payer_name: e.payerName || null,
  deposit_account: e.depositAccount || null,
  deposit_date: e.depositDate || null,
  trust_amount: e.trustAmount === '' || e.trustAmount == null ? null : Number(e.trustAmount),
  trust_remit_amount: e.trustRemitAmount === '' || e.trustRemitAmount == null ? null : Number(e.trustRemitAmount),
  note: e.note || null,
})
